name: Publish file to Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
      #              ^- 曜日 -> 月曜日
      #            ^- 月
      #          ^- 日
      #        ^- 時 -> 日本時間でちょうど午前9時
      #      ^- 分

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download file
        run: |
          mkdir -p public
          curl -L https://www.redmine.org/projects/redmine/news.atom -o public/redmine.atom

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
